# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170426_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[(b'Plants', b'Plants'), (b'Accessories', b'Accessories')], default=b'Plants', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 5, 10, 16, 56, 415843)),
        ),
        migrations.AlterField(
            model_name='plants',
            name='product_type',
            field=models.CharField(choices=[(b'Plants', b'Plants'), (b'Seeds', b'Seeds'), (b'Pots', b'Pots'), (b'Tools', b'Tools'), (b'Fertilizers', b'Fertilizers'), (b'Soil', b'Soil'), (b'Combos', b'Combos'), (b'Organic Compose', b'Organic Compose')], default=b'Plants', max_length=50),
        ),
    ]
