# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170506_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='diameter',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='width',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 12, 17, 45, 459336)),
        ),
    ]
