# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170513_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='shipping_info',
            field=models.TextField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 7, 50, 0, 320959)),
        ),
    ]
