# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170523_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='pot_size_max',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='pot_size_min',
        ),
        migrations.AddField(
            model_name='plants',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 30, 11, 49, 21, 27798)),
        ),
        migrations.AlterField(
            model_name='deliverychargeconfig',
            name='delivery_charge',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverychargeconfig',
            name='max_amount',
            field=models.PositiveIntegerField(verbose_name=b'Maximum amount for delivery charge'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Width/Length'),
        ),
    ]
