# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170530_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantstock',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 3, 14, 38, 54, 503098)),
        ),
        migrations.AlterField(
            model_name='plantstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
