# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170703_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 12, 12, 6, 44, 101559)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(b'payment_not_done', b'PAYMENT NOT DONE'), (b'payment_done', b'PAYMENT DONE'), (b'order_placed', b'ORDER PLACED'), (b'pending_customer_approval', b'PAINDING CUSTOMER APPROVAL'), (b'customer_approval_done', b'CUSTOMER_APPROVAL_DONE'), (b'in_process', b'IN PROCESS'), (b'dispatched', b'Dispatched'), (b'canceled', b'Canceled'), (b'delivered', b'DELIVERED')], default=b'payment_not_done', max_length=50),
        ),
    ]
