# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170712_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(upload_to=b'images/')),
            ],
            options={
                'verbose_name': 'Corporate Gift',
                'verbose_name_plural': 'Corporate Gift',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 28, 11, 35, 18, 237268)),
        ),
    ]
