# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170928_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='title_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 10, 10, 17, 687690)),
        ),
    ]
