# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-08 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171110_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineNersery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=250, null=True)),
                ('banner_image', models.ImageField(upload_to=b'images/')),
                ('meta_title', models.CharField(max_length=250, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('categories', models.ManyToManyField(to='core.Category', verbose_name=b'Select Category')),
            ],
            options={
                'verbose_name': 'Online Nursery',
                'verbose_name_plural': 'Online Nursery',
            },
        ),
        migrations.CreateModel(
            name='OnlineNerseryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('online_nersery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OnlineNersery')),
                ('plants', models.ManyToManyField(to='core.Plants', verbose_name=b'Select Plants')),
            ],
            options={
                'verbose_name': 'Online Nursery Category',
                'verbose_name_plural': 'Online Category',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 8, 6, 29, 24, 451285)),
        ),
    ]
