# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171208_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPagePromotionalBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to=b'images/')),
                ('banner_title', models.CharField(max_length=350, null=True)),
                ('link', models.CharField(max_length=350, null=True)),
            ],
            options={
                'verbose_name': 'Category page promotional banner',
                'verbose_name_plural': 'Category page promotional banner',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 23, 10, 11, 48, 271676)),
        ),
    ]
