# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-26 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180223_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 26, 14, 3, 16, 690034)),
        ),
    ]
