# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180226_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to=b'images/')),
                ('title', models.CharField(max_length=350, null=True)),
                ('link', models.CharField(max_length=350, null=True)),
                ('link_text', models.CharField(max_length=350, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Offer Slider',
                'verbose_name_plural': 'Offer Slider',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 7, 7, 51, 51, 982362)),
        ),
    ]
