# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-05 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180307_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 12, 58, 44, 121380)),
        ),
    ]
