# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-05 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180905_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 14, 33, 3, 496555)),
        ),
    ]
