# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-07 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180905_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 7, 11, 14, 23, 432696)),
        ),
    ]
