# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-12 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180907_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiwaliGifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('keyword', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('plants', models.ManyToManyField(to='core.Plants', verbose_name=b'Select Plants')),
            ],
            options={
                'verbose_name': 'Diwali Gifts Page',
                'verbose_name_plural': 'Diwali Gifts Page',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 12, 15, 15, 35, 743688)),
        ),
    ]
