# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-05 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181005_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 13, 19, 19, 521047)),
        ),
    ]
