# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-29 09:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181005_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='price_before_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'approved', b'Approved')], default=b'pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 29, 9, 6, 46, 878420)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
