# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-17 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181030_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plants',
            options={'ordering': ['-id'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 17, 12, 18, 32, 564288)),
        ),
    ]
