# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-02-15 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190917_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinenersery',
            name='long_content',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 16, 2, 2, 14677)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='plant_details',
            field=jsonfield.fields.JSONField(),
        ),
    ]
