# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-02-22 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210217_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 2, 1, 23, 959435)),
        ),
    ]
