# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210222_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('banner_text', models.TextField(default=None, max_length=500, null=True)),
                ('feature_text', models.TextField(default=None, max_length=500, null=True)),
                ('thumbnail', models.ImageField(default=b'images/product-image.jpg', upload_to=b'images/')),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('synonyms', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('title_tag', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('meta_keyword', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('long_contents', models.TextField(blank=True, default=None, max_length=25000, null=True)),
                ('video_url', models.URLField(default=None, max_length=500, null=True)),
                ('category_type', models.CharField(choices=[(b'Plants', b'Plants'), (b'Accessories', b'Accessories'), (b'Gifting', b'Gifting')], default=b'Plants', max_length=50)),
                ('custom_header_meta', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('custom_script_seo', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('benefits', models.ManyToManyField(to='core.Benefit')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Gifting')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 6, 7, 32, 797302)),
        ),
    ]
