# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210722_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gifting',
            options={'verbose_name': 'Gifting', 'verbose_name_plural': 'Giftings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 6, 12, 15, 808565)),
        ),
    ]
