# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210722_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 6, 22, 36, 72489)),
        ),
    ]
