# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210722_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('thumbnail', models.ImageField(default=b'images/product-image.jpg', upload_to=b'images/')),
                ('gifting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gifting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 7, 21, 25, 70639)),
        ),
    ]
