# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210722_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftingcategory',
            options={'verbose_name': 'GiftingCategory', 'verbose_name_plural': 'GiftingCategories'},
        ),
        migrations.AddField(
            model_name='giftingcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GiftingCategory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 7, 28, 23, 859699)),
        ),
    ]
