# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210722_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftingcategory',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 7, 31, 27, 282318)),
        ),
    ]
