# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210722_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftingcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GiftingCategory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 7, 37, 12, 128904)),
        ),
    ]
