# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210722_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftingCategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, null=True)),
                ('product_type', models.CharField(choices=[(b'Plants', b'Plants'), (b'Seeds', b'Seeds'), (b'Pots', b'Pots'), (b'Tools', b'Tools'), (b'Fertilizers', b'Fertilizers'), (b'Soil', b'Soil'), (b'Combos', b'Combos'), (b'Organic Compose', b'Organic Compose')], default=b'Plants', max_length=50)),
                ('actual_price', models.PositiveIntegerField(default=0)),
                ('price_before_sale', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('nutritional_value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('about', models.TextField(default=None, max_length=2500, null=True)),
                ('how_to_grow_soil_need', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('how_to_grow_fertilizer_type', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('how_to_grow_process', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('how_to_grow_growth_pattern', models.CharField(choices=[(b'Slow', b'Slow'), (b'Moderate', b'Moderate'), (b'Fast', b'Fast')], default=b'Slow', max_length=50)),
                ('how_to_grow_pruning', models.CharField(choices=[(b'Every Month', b'Every Month'), (b'1-2 Month', b'1-2 Month'), (b'2-3 Month', b'2-3 Month'), (b'3-4 Month', b'3-4 Month'), (b'4-5 Month', b'4-5 Month'), (b'5-6 Month', b'5-6 Month'), (b'6-7 Month', b'6-7 Month'), (b'7-8 Month', b'7-8 Month'), (b'8-9 Month', b'8-9 Month'), (b'9-10 Month', b'9-10 Month')], default=b'Every Month', max_length=50)),
                ('how_to_grow_re_potting', models.CharField(choices=[(b'Every 3-4 Month', b'Every 3-4 Month'), (b'Every 5-6 Month', b'Every 5-6 Month'), (b'Every 6-7 Month', b'Every 6-7 Month'), (b'Every 7-8 Month', b'Every 7-8 Month'), (b'Every 8-9 Month', b'Every 8-9 Month'), (b'Every 9-10 Month', b'Every 9-10 Month'), (b'Every 10-11 Month', b'Every 10-11 Month'), (b'Every 11-12 Month', b'Every 11-12 Month'), (b'Every 12-13 Month', b'Every 12-13 Month'), (b'Every 13-14 Month', b'Every 13-14 Month'), (b'Every 14-15 Month', b'Every 14-15 Month'), (b'Every 15-16 Month', b'Every 15-16 Month'), (b'Every 16-17 Month', b'Every 16-17 Month'), (b'Every 17-18 Month', b'Every 17-18 Month')], default=b'Every 3-4 Month', max_length=50)),
                ('maintenance_tip_do', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('maintenance_tip_dont', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('benefits', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('placement', models.CharField(choices=[(b'Outdoor-Sunny', b'Outdoor-Sunny'), (b'Outdoor-Shades', b'Outdoor-Shades'), (b'Indoor', b'Indoor'), (b'Outdoor-Sunny or Indoor', b'Outdoor-Sunny or Indoor'), (b'Outdoor-Shades or Indoor', b'Outdoor-Shades or Indoor'), (b'Anywhere', b'Anywhere')], default=b'Anywhere', max_length=50)),
                ('toxicity', models.CharField(blank=True, choices=[(b'YES', b'YES'), (b'NO', b'NO')], default=b'NO', max_length=100, null=True)),
                ('min_height', models.PositiveIntegerField(default=0)),
                ('max_height', models.PositiveIntegerField(default=0)),
                ('water_frequency_summer', models.CharField(choices=[(b'Alternate Day', b'Alternate Day'), (b'Daily', b'Daily'), (b'Twice Week', b'Twice Week'), (b'Weekly', b'Weekly'), (b'Monthly', b'Monthly')], default=b'Daily', max_length=150)),
                ('water_frequency_winter', models.CharField(choices=[(b'Alternate Day', b'Alternate Day'), (b'Daily', b'Daily'), (b'Twice Week', b'Twice Week'), (b'Weekly', b'Weekly'), (b'Monthly', b'Monthly')], default=b'Daily', max_length=150)),
                ('fertilizer_frequency_summer', models.CharField(choices=[(b'Every Month', b'Every Month'), (b'1-2 Month', b'1-2 Month'), (b'2-3 Month', b'2-3 Month'), (b'3-4 Month', b'3-4 Month'), (b'4-5 Month', b'4-5 Month'), (b'5-6 Month', b'5-6 Month'), (b'6-7 Month', b'6-7 Month'), (b'7-8 Month', b'7-8 Month'), (b'8-9 Month', b'8-9 Month'), (b'9-10 Month', b'9-10 Month'), (b'No', b'No')], default=b'No', max_length=150)),
                ('fertilizer_frequency_winter', models.CharField(choices=[(b'Every Month', b'Every Month'), (b'1-2 Month', b'1-2 Month'), (b'2-3 Month', b'2-3 Month'), (b'3-4 Month', b'3-4 Month'), (b'4-5 Month', b'4-5 Month'), (b'5-6 Month', b'5-6 Month'), (b'6-7 Month', b'6-7 Month'), (b'7-8 Month', b'7-8 Month'), (b'8-9 Month', b'8-9 Month'), (b'9-10 Month', b'9-10 Month'), (b'No', b'No')], default=b'No', max_length=150)),
                ('family_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('synonyms', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('fragrance', models.CharField(choices=[(b'Strong', b'Strong'), (b'Low', b'Low'), (b'Medium', b'Medium'), (b'None', b'None')], default=b'None', max_length=50)),
                ('plant_type', models.CharField(choices=[(b'Fruit', b'Fruit'), (b'Vegetable', b'Vegetable'), (b'None', b'None')], default=b'None', max_length=50)),
                ('flower', models.BooleanField(default=False)),
                ('flower_color', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('oxygen_sunlight', models.BooleanField(default=False)),
                ('oxygen_night', models.BooleanField(default=False)),
                ('stock', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Width/Length')),
                ('height', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('diameter', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('shipping_info', models.TextField(blank=True, default=None, max_length=4000, null=True)),
                ('title_tag', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('meta_keyword', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('product_sku', models.CharField(default=None, max_length=150, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('custom_header_meta', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('custom_script_seo', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('category', models.ManyToManyField(to='core.Category')),
                ('giftcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GiftingCategory')),
                ('maintenance_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MaintenanceLevel')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PriceCategory')),
                ('season', models.ManyToManyField(blank=True, default=None, to='core.Season')),
                ('tags', models.ManyToManyField(to='core.Tags')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'GiftingCategoryProduct',
                'verbose_name_plural': 'GiftingCategoryProduct',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 9, 17, 47, 638503)),
        ),
    ]
