# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210722_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifting',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='gifting',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='giftingcategoryproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='giftingcategoryproduct',
            name='giftcategory',
        ),
        migrations.RemoveField(
            model_name='giftingcategoryproduct',
            name='maintenance_level',
        ),
        migrations.RemoveField(
            model_name='giftingcategoryproduct',
            name='price_category',
        ),
        migrations.RemoveField(
            model_name='giftingcategoryproduct',
            name='season',
        ),
        migrations.RemoveField(
            model_name='giftingcategoryproduct',
            name='tags',
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 12, 44, 9, 374420)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[(b'Plants', b'Plants'), (b'Accessories', b'Accessories'), (b'Gifting', b'Gifting')], default=b'Plants', max_length=50),
        ),
        migrations.AlterField(
            model_name='giftingcategory',
            name='gifting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.DeleteModel(
            name='Gifting',
        ),
        migrations.DeleteModel(
            name='GiftingCategoryProduct',
        ),
    ]
