# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-22 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210722_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='giftcategory',
            field=models.ManyToManyField(to='core.GiftingCategory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 13, 30, 25, 169112)),
        ),
        migrations.AlterField(
            model_name='plants',
            name='product_type',
            field=models.CharField(choices=[(b'Plants', b'Plants'), (b'Seeds', b'Seeds'), (b'Pots', b'Pots'), (b'Tools', b'Tools'), (b'Fertilizers', b'Fertilizers'), (b'Soil', b'Soil'), (b'Combos', b'Combos'), (b'Organic Compose', b'Organic Compose'), (b'Organic Compose', b'Organic Compose'), (b'GiftingCategory', b'GiftingCategory')], default=b'Plants', max_length=50),
        ),
    ]
