# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[(b'monetary', b'Money based coupon'), (b'percentage', b'Percentage discount')], max_length=20, verbose_name='Type'),
        ),
    ]
