# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20170426_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximum Discount'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_no_of_item',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum Number Of Item'),
        ),
    ]
