# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20170712_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponuser',
            options={'ordering': ['redeemed_at'], 'verbose_name': 'Coupon User', 'verbose_name_plural': 'Coupon User'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Per User limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='User limit'),
        ),
        migrations.AlterUniqueTogether(
            name='couponuser',
            unique_together=set([]),
        ),
    ]
