"""
Django settings for greenDecor project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import environ
root = environ.Path(__file__) - 0 # three folder back (/a/b/c/ - 3 = /)
# env = environ.Env(DEBUG=(bool, False),) # set default values and casting
env = environ.Env(DEBUG=(bool, True),) # set default values and casting
environ.Env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# ALLOWED_HOSTS = ['www.greendecor.in','3.6.92.206']
ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
            'admin_tools',
                'admin_tools.theming',
                    'admin_tools.dashboard',
                        'django.contrib.admin',
                            'django.contrib.auth',
                                'django.contrib.contenttypes',
                                    'django.contrib.sessions',
                                        'django.contrib.messages',
                                            'django.contrib.staticfiles',
                                                'django.contrib.algoliasearch',
                                                    'core.apps.CoreConfig',
                                                        'social_django',
                                                            'rest_framework',
                                                                'rest_framework.authtoken',
                                                                    'corsheaders',
                                                                        'tinymce',
                                                                            'coupon.apps.CouponConfig',
                                                                                'djangobower',
                                                                                    'admin_tools_stats',
                                                                                        'django_nvd3',
                                                                                            'import_export',
                                                                                            'loginas'
                                                                                            ]

ALGOLIA = {
            'APPLICATION_ID': env('ALGOLIA_APPLICATION_ID'),
                'API_KEY': env('ALGOLIA_API_KEY')
                }
# BOWER_COMPONENTS_ROOT = os.path.join(BASE_DIR, 'components')
# BOWER_PATH = '/usr/local/bin/bower'
BOWER_INSTALLED_APPS = (
            'jquery#2.0.3',
                'jquery-ui#~1.10.3',
                    'd3#3.3.6',
                        'nvd3#1.1.12-beta',
                        )

STATICFILES_FINDERS = (
            'django.contrib.staticfiles.finders.FileSystemFinder',
                'django.contrib.staticfiles.finders.AppDirectoriesFinder',
                    'djangobower.finders.BowerFinder',
                    )

#DJANGO-ADMIN-TOOL
#=================
ADMIN_TOOLS_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'
ADMIN_TOOLS_APP_INDEX_DASHBOARD = 'dashboard.CustomAppIndexDashboard'
ADMIN_MEDIA_PREFIX = '/static/admin/'


MIDDLEWARE = [
            'django.middleware.security.SecurityMiddleware',
                'django.contrib.sessions.middleware.SessionMiddleware',
                    'django.middleware.common.CommonMiddleware',
                        'django.middleware.csrf.CsrfViewMiddleware',
                            'django.contrib.auth.middleware.AuthenticationMiddleware',
                                'django.contrib.messages.middleware.MessageMiddleware',
                                    'django.middleware.clickjacking.XFrameOptionsMiddleware',
                                        'corsheaders.middleware.CorsMiddleware',
                                            'django.middleware.common.CommonMiddleware',
                                            ]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'greenDecor.urls'

TEMPLATES = [
            {
                    'BACKEND': 'django.template.backends.jinja2.Jinja2',
                        'DIRS': [os.path.join(BASE_DIR, 'templates')],
                            'APP_DIRS': True,
                                'OPTIONS': {
                                            'environment': "greenDecor.jinja2.environment",
                                                },
                                },
            {
                        'BACKEND': 'django.template.backends.django.DjangoTemplates',
                                'DIRS':[os.path.join(BASE_DIR, 'templates')],
                                        # 'APP_DIRS': True,
                                                'OPTIONS': {
                                                                'context_processors': [
                                                                                    'django.template.context_processors.debug',
                                                                                                    'django.template.context_processors.request',
                                                                                                                    'django.contrib.auth.context_processors.auth',
                                                                                                                                    'django.contrib.messages.context_processors.messages',
                                                                                                                                                ],
                                                                            'loaders': [
                                                                                                ('django.template.loaders.cached.Loader', [
                                                                                                                    'django.template.loaders.filesystem.Loader',
                                                                                                                                    'django.template.loaders.app_directories.Loader',
                                                                                                                                                    'django.template.loaders.eggs.Loader',
                                                                                                                                                                    'admin_tools.template_loaders.Loader',
                                                                                                                                                                                ]),
                                                                                                            ]
                                                                                    },
                                                    },
            ]


WSGI_APPLICATION = 'greenDecor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#                     'default': env.db(),
#
#                     }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'greendecor2',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
            {
                        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
                            },
                {
                            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
                                },
                    {
                                'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
                                    },
                        {
                                    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
                                        },
                        ]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/


STATIC_ROOT=os.path.join(BASE_DIR,'static/')
STATIC_URL = '/static/'
STATICFILES_DIRS=['static_files',]

MEDIA_ROOT=os.path.join(BASE_DIR,'media/')
MEDIA_URL='/media/'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'


# social setting
# SOCIAL_AUTH_URL_NAMESPACE = 'social'
AUTHENTICATION_BACKENDS = (
            'django.contrib.auth.backends.ModelBackend',
                'social_core.backends.open_id.OpenIdAuth',
                    'social_core.backends.google.GoogleOpenId',
                        'social_core.backends.google.GoogleOAuth2',
                            'social_core.backends.google.GoogleOAuth',
                                'social_core.backends.facebook.FacebookOAuth2',
                                )
SOCIAL_AUTH_SANITIZE_REDIRECTS = False
SOCIAL_AUTH_FACEBOOK_KEY = env('FB_SOCIAL_AUTH_KEY')
# '793041757509553'
SOCIAL_AUTH_FACEBOOK_SECRET = env('FB_SOCIAL_AUTH_SECRET_KEY')
# '77a9de0c25c592d1453c11e5a65d0ec0'

SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
          'locale': 'ru_RU',
            'fields': 'id, name, email'
            }
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env('GOOGLE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
# '758014244553-9tufia7kvvhek5p72uivr7c3vv72ketl.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env('GOOGLE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
# '9ZfQ3YgHFqW3NpdgKOece7_T'
USE_X_FORWARDED_HOST = True

SOCIAL_AUTH_NEW_USER_REDIRECT_URL='/login/social'

SERVER_ADDRESS='https://www.greendecor.in/'
SERVER_ADDRESS_WITHOUT_SLASH='https://www.greendecor.in'



USEEMAIL= env('USEEMAIL')
EMAIL_USE_TLS = True
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = env('USEEMAIL')
EMAIL_HOST_PASSWORD =env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = USEEMAIL
# DEFAULT_TO_EMAIL = 'javedahamad4@gmail.com'
DEFAULT_TO_EMAIL = env('DEFAULT_TO_EMAIL')
EMAIL_BACKEND = env('EMAIL_BACKEND')

CAN_LOGIN_AS = lambda request, target_user: request.user.is_superuser
from django.urls  import reverse_lazy
LOGINAS_LOGOUT_REDIRECT_URL = reverse_lazy('admin:index')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/codetrade/Desktop/SUNIT/greendecor.in-master/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

